apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  # This is an extra long description with Markdown
  description: |
    [The Petstore](http://petstore.example.com) is an example API used to show features of the OpenAPI spec.
    - First item
    - Second item
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
  annotations:
    nexus-repository-manager/repository: maven-snapshots
    # nexus-repository-manager/format: maven2
    # nexus-repository-manager/group: uk.mod.d2s
    # nexus-repository-manager/name: openshift-service
    # nexus-repository-manager/version: 12.1.3-20241008.113145-1
spec:
  type: service
  lifecycle: experimental
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
